[versions]
agp = "9.2.0"
kotlin = "2.4.10"
jdk = "17"
compileSdk = "36"
targetSdk = "36"
minSdk = "26"
buildTools = "36.0.0"
composeBom = "2026.08.00"

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
