package dev.hryshyn.remanence.core.model

object ProtocolV1Limits {
    const val PROTOCOL_VERSION = 1
    const val EMAIL_MAX_UTF8_BYTES = 254
    const val PASSWORD_MIN_CODE_POINTS = 12
    const val PASSWORD_MAX_CODE_POINTS = 128
    const val HANDLE_MIN_ASCII_CHARS = 3
    const val HANDLE_MAX_ASCII_CHARS = 30
    const val NOTE_MAX_UTF8_BYTES = 1000
    const val PLACE_LABEL_MAX_UTF8_BYTES = 120
    const val PHOTO_COUNT_MIN = 3
    const val PHOTO_COUNT_MAX = 5
    const val PHOTO_ORDINAL_MIN = 0
    const val PHOTO_ORDINAL_MAX = 4
    const val NON_PHOTO_ORDINAL = -1
    const val RECOGNITION_MANIFEST_COUNT = 1
    const val CONTENT_MANIFEST_COUNT = 1
    const val RECIPIENT_ENVELOPE_COUNT = 1
    const val NORMALIZED_PHOTO_MEDIA_TYPE = "image/jpeg"
    const val NORMALIZED_PHOTO_MAX_LONG_EDGE_PX = 2560
    const val NORMALIZED_PHOTO_MAX_PLAINTEXT_BYTES = 8_388_608L
    const val ARTIFACT_AEAD_OVERHEAD_BYTES = 33L
    const val ENCRYPTED_PHOTO_MAX_CIPHERTEXT_BYTES = 8_388_641L
    const val RECOGNITION_MANIFEST_MAX_CIPHERTEXT_BYTES = 1_048_576L
    const val CONTENT_MANIFEST_MAX_CIPHERTEXT_BYTES = 65_536L
    const val RECIPIENT_ENVELOPE_MAX_CIPHERTEXT_BYTES = 16_384L
    const val TOTAL_CAPSULE_MAX_CIPHERTEXT_BYTES = 44_040_192L
    const val DRAFT_LIFETIME_SECONDS = 604_800L
    const val INCOMING_PAGE_DEFAULT = 50
    const val INCOMING_PAGE_MAX = 100
    const val MVP_TRACK_ATTACHMENT_ALLOWED = false

    internal const val ENCRYPTED_PHOTO_PLAINTEXT_PLUS_OVERHEAD_BYTES =
        NORMALIZED_PHOTO_MAX_PLAINTEXT_BYTES + ARTIFACT_AEAD_OVERHEAD_BYTES
}
