package dev.hryshyn.remanence.ui.create

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.google.crypto.tink.TinkProtoKeysetFormat
import com.google.crypto.tink.subtle.Base64
import dev.hryshyn.remanence.capture.CaptureAttemptController
import dev.hryshyn.remanence.capture.PreparedBackItem
import dev.hryshyn.remanence.capture.ProcessedStill
import dev.hryshyn.remanence.capture.StillProcessor
import dev.hryshyn.remanence.core.crypto.AccountIdentityGenerator
import dev.hryshyn.remanence.core.crypto.RecipientEnvelopeCryptor
import dev.hryshyn.remanence.core.crypto.TinkPrimitives
import dev.hryshyn.remanence.core.data.db.OutboxCapsuleState
import dev.hryshyn.remanence.core.data.db.RemanenceLocalDatabase
import dev.hryshyn.remanence.core.data.fingerprints.SealedFingerprintPersistence
import dev.hryshyn.remanence.core.data.network.DirectoryLookupResult
import dev.hryshyn.remanence.core.data.network.ResolvedHandleSnapshot
import dev.hryshyn.remanence.core.model.CapsuleId
import dev.hryshyn.remanence.core.model.KeyBundleId
import dev.hryshyn.remanence.core.model.NormalizedHandle
import dev.hryshyn.remanence.core.model.RecipientEnvelopeContextInput
import dev.hryshyn.remanence.core.model.UserId
import dev.hryshyn.remanence.core.recognition.FingerprintSide
import dev.hryshyn.remanence.core.recognition.FingerprintKeypoint
import dev.hryshyn.remanence.core.recognition.PostcardFingerprint
import dev.hryshyn.remanence.core.recognition.RecognitionProfile
import dev.hryshyn.remanence.core.recognition.ExtractionQuality
import dev.hryshyn.remanence.core.recognition.FingerprintCodec
import dev.hryshyn.remanence.auth.SoftwareKekBoundary
import dev.hryshyn.remanence.core.crypto.SenderRetryKeysetWrapper
import dev.hryshyn.remanence.core.data.storage.SenderRetryMaterialStore
import java.io.File
import java.util.UUID
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.test.UnconfinedTestDispatcher
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Assert.fail
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * M2-P07 production-shaped proof that the publisher reads the recipient
 * identity, recipient key-bundle id, and recipient encryption public keyset
 * ONLY from the explicitly confirmed immutable [ResolvedHandleSnapshot]
 * captured into the [PublishInputs] before any suspend boundary. The sender
 * fields - sender user id, signing key, sender handle, and owner user id -
 * remain the authenticated local account.
 *
 * A self-send is still valid because the user may confirm their OWN handle:
 * the captured snapshot is then equal-valued to the sender and the
 * publisher sees EQUAL values rather than a default. The two cross-identity
 * tests below pin the distinct-recipient path so no future refactor can
 * silently rewrite the captured snapshot back to the sender identity.
 *
 * Every test runs through the production [CreateViewModel] over the real
 * Room database, the real capsule outbox stager, and real Tink keysets
 * generated by [AccountIdentityGenerator].
 */
@OptIn(ExperimentalCoroutinesApi::class)
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class CreateRecipientPublicationBindingTest {

    private val testDispatcher = UnconfinedTestDispatcher()

    private val senderIdentity = AccountIdentityGenerator().generate()
    private val recipientIdentity = AccountIdentityGenerator().generate()

    private val senderUserUuid = UUID.fromString("9e111111-2222-4333-8444-555555555555")
    private val senderBundleUuid = UUID.fromString("9e333333-4444-4555-8666-777777777777")
    private val recipientUserUuid = UUID.fromString("9f111111-2222-4333-8444-555555555555")
    private val recipientBundleUuid = UUID.fromString("9f333333-4444-4555-8666-777777777777")

    private lateinit var database: RemanenceLocalDatabase
    private lateinit var stagingDir: File
    private lateinit var outboxDir: File

    private val testKekBoundary = SoftwareKekBoundary()
    private val testAlias = "test-sender-retry-${java.util.UUID.randomUUID()}"
    private lateinit var testWrapper: SenderRetryKeysetWrapper

    @Before
    fun setUp() {
        testKekBoundary.createAes256GcmKey(testAlias)
        testWrapper = SenderRetryKeysetWrapper(testKekBoundary)
        Dispatchers.setMain(testDispatcher)
        TinkPrimitives.ensureRegistered()
        val context = ApplicationProvider.getApplicationContext<Context>()
        database = Room.inMemoryDatabaseBuilder(context, RemanenceLocalDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        stagingDir = File(context.filesDir, "recipient-binding-staging").apply { mkdirs() }
        outboxDir = File(context.filesDir, "recipient-binding-outbox")
    }

    @After
    fun tearDown() {
        Dispatchers.resetMain()
        if (::database.isInitialized) database.close()
        stagingDir.deleteRecursively()
        outboxDir.deleteRecursively()
    }

    private fun b64Url(bytes: ByteArray): String = Base64.urlSafeEncode(bytes)

    private fun recipientSnapshot(): ResolvedHandleSnapshot = ResolvedHandleSnapshot(
        userId = UserId(recipientUserUuid),
        handle = NormalizedHandle.parse("friend"),
        keyBundleId = KeyBundleId(recipientBundleUuid),
        suite = "HPKE_X25519_HKDF_SHA256_AES256GCM__ED25519",
        protocolVersion = 1,
        encryptionPublicKeysetB64Url = b64Url(recipientIdentity.encryptionPublicKeyset),
        signingPublicKeysetB64Url = b64Url(recipientIdentity.signingPublicKeyset),
        keyBundleStatus = "ACTIVE",
        directoryVersion = "v1",
    )

    private class StaticDirectory : RecipientDirectoryPort {
        override suspend fun lookup(rawHandle: String): DirectoryLookupResult =
            DirectoryLookupResult.NotFound
    }

    private class Accepting(private val side: FingerprintSide) : StillProcessor {
        override fun process(jpegBytes: ByteArray): ProcessedStill = synthetic(side)
    }

    private class RecordingPersistence : SealedFingerprintPersistence {
        val stored = mutableMapOf<String, ByteArray>()
        var counter = 0

        override suspend fun persist(
            capsuleId: String,
            side: dev.hryshyn.remanence.core.data.db.FingerprintSide,
            origin: dev.hryshyn.remanence.core.data.db.FingerprintOrigin,
            profileId: String,
            plaintextBytes: ByteArray,
        ): String {
            val id = "fp-${++counter}"
            stored[id] = plaintextBytes
            return id
        }

        override suspend fun hasBaseline(
            capsuleId: String,
            side: dev.hryshyn.remanence.core.data.db.FingerprintSide,
            origin: dev.hryshyn.remanence.core.data.db.FingerprintOrigin,
        ): Boolean = stored.isNotEmpty()

        override suspend fun decrypt(fingerprintId: String): ByteArray =
            requireNotNull(stored[fingerprintId])

        override suspend fun setPreferredPair(
            capsuleId: String,
            origin: dev.hryshyn.remanence.core.data.db.FingerprintOrigin,
        ) = Unit

        override suspend fun deleteBaseline(
            capsuleId: String,
            side: dev.hryshyn.remanence.core.data.db.FingerprintSide,
            origin: dev.hryshyn.remanence.core.data.db.FingerprintOrigin,
        ) = Unit
    }

    /**
     * Drives one create session through FRONT + BACK + CONTENT and lands the
     * VM at CONTENT with the given [snapshot] bound into the confirmed
     * recipient store. The sender identity is the local account under test.
     */
    private fun contentStageForRecipient(
        snapshot: ResolvedHandleSnapshot,
    ): CreateViewModel {
        val persistence = RecordingPersistence()
        val retryStore = SenderRetryMaterialStore(dev.hryshyn.remanence.core.data.storage.AccountScopedFileRoots(outboxDir))
        val vm = CreateViewModel(
            directory = StaticDirectory(),
            accessTokenProvider = { null },
            identityProvider = {
                SenderIdentitySnapshot(
                    userId = senderUserUuid.toString(),
                    handle = "mykola",
                    activeKeyBundleId = senderBundleUuid.toString(),
                    encryptionPrivateHandle = senderIdentity.encryptionPrivateHandle,
                    signingPrivateHandle = senderIdentity.signingPrivateHandle,
                )
            },
            persistence = persistence,
            outboxStager = dev.hryshyn.remanence.core.data.outbox.CapsuleOutboxStager(
                database,
                dev.hryshyn.remanence.core.data.storage.AccountScopedFileRoots(outboxDir),
                retryStore,
            ),
            profile = RecognitionProfile.mvpOrbV1(),
            accountScopedFileRoots = dev.hryshyn.remanence.core.data.storage.AccountScopedFileRoots(stagingDir),
            openPhotoSource = { id ->
                dev.hryshyn.remanence.create.PhotoSource {
                    java.io.ByteArrayInputStream("photo-$id".toByteArray())
                }
            },
            frontProcessor = Accepting(FingerprintSide.FRONT),
            backProcessor = Accepting(FingerprintSide.BACK),
            photoNormalizer = { input ->
                dev.hryshyn.remanence.create.NormalizedPhotoDto(input.copyOf(), 800, 600)
            },
            cpuDispatcher = testDispatcher,
            ioDispatcher = testDispatcher,
            senderRetryKeysetWrapper = testWrapper,
            senderRetryKekAlias = testAlias,
            enqueueUpload = { _, _ -> },
        )
        vm.beginSession(1L, senderUserUuid.toString())
        vm.onResolved(snapshot)
        vm.confirmRecipient()
        vm.frontAttempt.onPermissionResult(true, false)
        vm.frontAttempt.onPreviewBound()
        assertTrue(vm.beginFrontCapture())
        vm.deliverFrontJpeg("f".toByteArray())
        PreparedBackItem.entries.forEach { item -> vm.backGate.setChecked(item, true) }
        vm.proceedToBackChecklist()
        vm.backAttempt.onPermissionResult(true, false)
        vm.backAttempt.onPreviewBound()
        assertTrue(vm.beginBackCapture())
        vm.deliverBackJpeg("b".toByteArray())
        assertEquals(CreateViewModel.Step.CONTENT, vm.step.value)
        vm.onPhotosPicked(listOf("p1", "p2", "p3"))
        assertTrue(vm.noteEditor.onChange("binding note"))
        return vm
    }

    private fun awaitTerminalPublish(vm: CreateViewModel) {
        val deadline = System.currentTimeMillis() + 10_000
        while (vm.step.value == CreateViewModel.Step.PUBLISHING) {
            if (System.currentTimeMillis() > deadline) {
                error("publishing never reached a terminal step; publishError=" + vm.publishError.value)
            }
            Thread.sleep(20)
        }
    }

    private suspend fun outboxRow(capsuleId: String) =
        database.outboxCapsuleDao().getByCapsuleIdAndOwner(capsuleId, senderUserUuid.toString())

    // ------------------------------------------------------------------
    // M2-P07 cross-identity publication proof.
    // ------------------------------------------------------------------

    @Test
    fun distinctRecipientSnapshotProducesSenderAOwnerARecipientBBundle() = runBlocking {
        val vm = contentStageForRecipient(recipientSnapshot())
        val capsuleId = vm.capsuleId

        vm.startPublishing()
        awaitTerminalPublish(vm)

        assertEquals(
            "publishing must complete when the captured recipient is distinct from the sender",
            CreateViewModel.Step.UPLOAD_PENDING,
            vm.step.value,
        )
        assertTrue(vm.publishError.value == null)
        assertTrue(vm.flowError.value == null)

        val row = requireNotNull(outboxRow(capsuleId)) { "outbox row was not staged" }
        assertEquals(OutboxCapsuleState.ENCRYPTED, row.state)

        // Sender half stays the authenticated local account.
        assertEquals(senderUserUuid.toString(), row.senderUserId)
        assertEquals(senderBundleUuid.toString(), row.senderKeyBundleId)
        assertEquals(senderUserUuid.toString(), row.ownerUserId)

        // Recipient half is the confirmed snapshot - DISTINCT from the sender.
        assertEquals(recipientUserUuid.toString(), row.recipientUserId)
        assertEquals(recipientBundleUuid.toString(), row.recipientKeyBundleId)
        assertNotEquals(row.senderUserId, row.recipientUserId)
        assertNotEquals(row.senderKeyBundleId, row.recipientKeyBundleId)
        assertNotEquals(row.ownerUserId, row.recipientUserId)
    }

    @Test
    fun distinctRecipientEnvelopeIsSealedToTheBoundRecipientAndSenderCannotOpenIt() = runBlocking {
        val vm = contentStageForRecipient(recipientSnapshot())
        val capsuleId = vm.capsuleId

        vm.startPublishing()
        awaitTerminalPublish(vm)
        assertEquals(CreateViewModel.Step.UPLOAD_PENDING, vm.step.value)

        val row = requireNotNull(outboxRow(capsuleId))
        val envelopeBytes = File(requireNotNull(row.envelopePath)).readBytes()
        assertTrue("envelope must be a real ciphertext blob", envelopeBytes.isNotEmpty())

        // The bound recipient's PRIVATE key + the distinct recipient context
        // opens the envelope. This is the only key that MUST open it.
        val openedForRecipient = RecipientEnvelopeCryptor().open(
            recipientIdentity.encryptionPrivateHandle,
            RecipientEnvelopeContextInput(
                CapsuleId(UUID.fromString(capsuleId)),
                UserId(senderUserUuid),
                UserId(recipientUserUuid),
                KeyBundleId(recipientBundleUuid),
            ),
            envelopeBytes,
        )
        assertTrue(
            "envelope must open for the bound recipient",
            openedForRecipient.isNotEmpty(),
        )

        // The SENDER's private encryption key, asked to open the envelope
        // addressed to the recipient, FAILS. The recipient identity is
        // genuinely bound into the envelope AAD, not conflated with the
        // sender's.
        val senderOpen = runCatching {
            RecipientEnvelopeCryptor().open(
                senderIdentity.encryptionPrivateHandle,
                RecipientEnvelopeContextInput(
                    CapsuleId(UUID.fromString(capsuleId)),
                    UserId(senderUserUuid),
                    UserId(recipientUserUuid),
                    KeyBundleId(recipientBundleUuid),
                ),
                envelopeBytes,
            )
        }
        assertTrue(
            "sender's private key must not open an envelope addressed to another user",
            senderOpen.isFailure,
        )

        // The recipient's key, asked to open with a SELF-send context
        // (recipient == sender), also FAILS. The recipient identity is
        // bound independently into the AAD; the publisher's recipient input
        // is not silently rewritten to the sender.
        val selfContextOpen = runCatching {
            RecipientEnvelopeCryptor().open(
                recipientIdentity.encryptionPrivateHandle,
                RecipientEnvelopeContextInput(
                    CapsuleId(UUID.fromString(capsuleId)),
                    UserId(senderUserUuid),
                    UserId(senderUserUuid),
                    KeyBundleId(senderBundleUuid),
                ),
                envelopeBytes,
            )
        }
        assertTrue(
            "envelope addressed to a distinct recipient must reject a self-send context",
            selfContextOpen.isFailure,
        )
    }

    @Test
    fun selfConfirmedRecipientProducesSelfSendOutboxRow() = runBlocking {
        // M2-P07: a self-send is a valid publication path. The user confirms
        // their OWN handle; the publisher receives equal values for sender
        // and recipient (and equal key-bundle ids) explicitly, never as a
        // default. The outbox row carries sender == recipient == owner.
        val selfSnapshot = ResolvedHandleSnapshot(
            userId = UserId(senderUserUuid),
            handle = NormalizedHandle.parse("mykola"),
            keyBundleId = KeyBundleId(senderBundleUuid),
            suite = "HPKE_X25519_HKDF_SHA256_AES256GCM__ED25519",
            protocolVersion = 1,
            encryptionPublicKeysetB64Url = b64Url(senderIdentity.encryptionPublicKeyset),
            signingPublicKeysetB64Url = b64Url(senderIdentity.signingPublicKeyset),
            keyBundleStatus = "ACTIVE",
            directoryVersion = "v1",
        )
        val vm = contentStageForRecipient(selfSnapshot)
        val capsuleId = vm.capsuleId

        vm.startPublishing()
        awaitTerminalPublish(vm)

        assertEquals(CreateViewModel.Step.UPLOAD_PENDING, vm.step.value)
        val row = requireNotNull(outboxRow(capsuleId))
        assertEquals(senderUserUuid.toString(), row.senderUserId)
        assertEquals(senderUserUuid.toString(), row.recipientUserId)
        assertEquals(senderUserUuid.toString(), row.ownerUserId)
        assertEquals(senderBundleUuid.toString(), row.senderKeyBundleId)
        assertEquals(senderBundleUuid.toString(), row.recipientKeyBundleId)

        // The self-send envelope still opens for the only key that has a
        // right to open it - the local account's own encryption private key.
        val envelopeBytes = File(requireNotNull(row.envelopePath)).readBytes()
        val opened = RecipientEnvelopeCryptor().open(
            senderIdentity.encryptionPrivateHandle,
            RecipientEnvelopeContextInput(
                CapsuleId(UUID.fromString(capsuleId)),
                UserId(senderUserUuid),
                UserId(senderUserUuid),
                KeyBundleId(senderBundleUuid),
            ),
            envelopeBytes,
        )
        assertTrue(opened.isNotEmpty())
    }

    companion object {
        private fun synthetic(side: FingerprintSide): ProcessedStill.Accepted {
            val profile = RecognitionProfile.mvpOrbV1()
            val keypoints = List(64) {
                FingerprintKeypoint(
                    xNormalized = (it % 8) / 8.0,
                    yNormalized = (it / 8) / 8.0,
                    scaleNormalized = 1.0,
                    angleCentiDegrees = 0,
                    responseQuantized = it,
                    octave = 0,
                )
            }
            return ProcessedStill.Accepted(
                profileId = profile.profileId,
                serializedBytes = FingerprintCodec.serialize(
                    PostcardFingerprint(
                        profileId = profile.profileId,
                        canonicalWidthPx = profile.capture.canonicalLongEdgePx,
                        canonicalHeightPx = 1000,
                        coarseHash64 = 6L,
                        keypoints = keypoints,
                        descriptors = List(64) { i ->
                            ByteArray(32) { ((it * 17 + i * 5) and 0xFF).toByte() }
                        },
                        quality = ExtractionQuality(200.0, 90.0, 0.01, 0.85),
                    ),
                ),
            )
        }
    }
}
